homePage/urls.py
from django.conf.urls import url
from django.urls.conf import path

from django.views.generic.base import RedirectView
from . import views 

app_name = 'homePage'
urlpatterns = [ 
    path('homepage/', views.homePage, name='homePage'),
    path(r'', RedirectView.as_view(url='homepage/', permanent=False), name='homePageDefault'), # tự động trỏ đến homepage nếu url để trống
    path('reading/', views.readingSite, name='readingSite'),
    path('readpage/<int:id>/', views.readPageSite, name='readPageSite'),
    path('post/', views.post, name='post'),
    path('note-book/', views.notebook, name='note-book') 
]

readingTime/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls, name='adminSite'),
    url(r'', include('signSite.urls')),#trỏ tiếp url đến file urls của signSite
    url(r'', include('homePage.urls')),#trỏ tiếp url đến file urls của homePage
]

signSite/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from usefulModels.getIdiom import getIdiom

from . import views 

app_name = 'signSite'
urlpatterns = [ 
    url('signup/', views.signUp, name='signUp'),
    url('signin/', auth_views.LoginView.as_view(template_name='signIn.html', extra_context={'title': 'Sign In', 'idiom4Day': getIdiom()}), name='signIn'),
    url('signout/', auth_views.LogoutView.as_view(template_name='signOut.html', extra_context={'title': 'Sign Out', 'idiom4Day': getIdiom()}), name='signOut'),
]

homePage/models.py
from django.db import models

# Create your models here.

homePage/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render

from django.http import HttpResponse
from usefulModels.forms import CommentForm, PostForm
from usefulModels.models import Comment, Post, ReadingBook, QuesModel, Vocabulary

#Tạo render cho HOME
def homePage(request):
    object_list = ReadingBook.objects.all()
    return render(
        request,
        'homePage.html',
        {'object_list':object_list,}
        )

#Tạo render cho READING    
def readingSite(request):
    object_view = ReadingBook.objects.all()
    object_view1 = ReadingBook.objects.filter(category__name = 'Funny Story')
    object_view2 = ReadingBook.objects.filter(category__name = 'Jokes')
    object_view3 = ReadingBook.objects.filter(category__name = 'Children Story')
    return render (
        request,
        'readingSite.html',{
        'object_view': object_view,
        'object_view1' : object_view1,
        'object_view2' :object_view2,
        'object_view3' :object_view3,
        }
    ) 

#Tạo render cho READPAGE
def readPageSite(request, id):
    if request.method == 'POST':
        if request.POST.get('note'):
            object_views = ReadingBook.objects.get(id = id)
            create_notes = Post.objects.create(
                author=request.user,
                name_read=object_views,
                note=request.POST.get('note'),
            )
            post = Post.objects.filter(author=request.user)
            return render(
                request,
                'note-book.html',
                {'post':post,}
                )
        else:
            print(request.POST)
            questions=QuesModel.objects.filter(name_read_id = id)
            score=0
            wrong=0
            correct=0
            total=0
            for q in questions:
                total+=1
                print(request.POST.get(q.question))
                print(q.ans)
                print()
                if q.ans ==  request.POST.get(q.question):
                    score+=10
                    correct+=1
                else:
                    wrong+=1
            percent = score/(total*10) *100
            context = {
                'score':score,
                'time': request.POST.get('timer'),
                'correct':correct,
                'wrong':wrong,
                'percent':percent,
                'total':total
            }
            return render(request,'kq.html', context)
    else:
        object_views = ReadingBook.objects.get(id = id)
        questions= QuesModel.objects.filter(name_read_id = id)
        vocabulary= Vocabulary.objects.filter(name_read_id = id)
        object_views.views += 1
        object_views.save()

        context = {
            'questions':questions,
            'object_views': object_views,
            'vocabulary': vocabulary,
        }
        return render(request,'readPageSite.html', context)

def post(request):
    postt = Comment.objects.all()
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST, author=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path)
    return render(request, "post.html", {"postt": postt, "form": form})

def notebook(request):
    post = Post.objects.filter(author=request.user)
    return render(
        request,
        'note-book.html',
        {'post':post,}
        )

templates/base_homeSite.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RT-Dashboard</title>
    <link rel="stylesheet" href="{% static 'icon/themify-icons/themify-icons.css' %}">
    {% block stylecss %}{% endblock %}


</head>

<body >
    <div id="main">
        <div id="sidebar">
            <ul id="sidebar-menu">
                <br><br><br>
                <li><a href="{% url 'homePage:homePage' %}">
                        <i class="ti-home"></i>
                        <label>Home</label>
                    </a></li>
                <li><a href="{% url 'homePage:readingSite' %}">
                        <i class="ti-book"></i>
                        <label>Reading</label>
                    </a></li>
                <li><a href="{% url 'homePage:note-book' %}">
                        <i class="ti-notepad"></i>
                        <label>Notebook</label>
                    </a></li>
                <li><a href="{% url 'homePage:post' %}">
                        <i class="ti-settings"></i>
                        <label>Settings</label>
                    </a></li>
                <li><a href="{% url 'signSite:signOut' %}">
                        <i class="ti-user"></i>
                        <label>Log out</label>
                    </a></li>
            </ul>
        </div>
        <div id="content-layout">
            <div id="content" >
       {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    {% block jscript %}{% endblock %}
</body>

</html>

templates/base_signSite.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- thêm css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles_signSite.css' %}" />

    <!-- tùy chỉnh title -->
    {% if title %}
    <title>Reading Time - {{ title }}</title>
    {% else %}
    <title>Reading Time</title>
    {% endif %}
</head>

<body>
    <div id="main">
        <div id="content">
            <div id="idiom">
                {% include "idiom4Day.html" %}
            </div>
            <div id="signSite">
                {% block signSite %}{% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

templates/homePage.html
{% extends "base_homeSite.html" %}

{% load static %}
{% block stylecss %}
<link rel="stylesheet" href="{% static 'css/homePage.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% endblock stylecss %}

{% block content %}
<div id="content-info">
    <h1>Reading Time</h1>
    <p>This is a website where you improve your reading skills through short stories</p>
    <p>Have fun with the Reading Time</p>
</div>
<div id="content-top">
    <div id="userInfo" class="content-top-item">
        <h2>{{ request.user }}</h2>
        <div class="item-container">
            <div class="user-info-item">
                <p class="p1">Course</p>
                <p class="p2">30/100</p>
            </div>
            <div class="user-info-item">
                <p class="p1">Scores</p>
                <p class="p2">123</p>
            </div>
            <div class="user-info-item">
                <p class="p1">Vocabulary</p>
                <p class="p2">13</p>
            </div>
        </div>
    </div>
    <div id="idiom" class="content-top-item">
        <p class="idiom-idiom">Break a leg!</p>
        <p class="idiom-meaning">Good luck! (an expression that is used in theater
            performances.)</p>
    </div>
</div>
<div class="mt-4 container">
    <div id="content-main " class="row">
        {% for item in object_list %}
        <div class="lesson col-sm-6 col-lg-4" style="margin-right: 30px;">
            <div>
                <a href="{% url 'homePage:readPageSite' item.id %}">
                    <h2>{{ item.name }}</h2>
                    <i class="">views : {{ item.views }}</i>
                    <p>Status: unread/reading/done</p>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div id="content-bot">
</div>
{% endblock content %}

templates/idiom4Day.html
<div>
    <h2 id="idiom_sentence">{{ idiom4Day.idiom_sentence }}</h2>
    <p id="idiom_meaning">{{ idiom4Day.idiom_meaning }}</p>
</div>

templates/kq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        <h5 class="card-title">Score: {{score}}</h5>

        <p class="card-text">Percentage: {{percent}}%</p>
        <p class="card-text">Time Taken: {{time}} seconds</p>
        <p class="card-text">Correct answers: {{correct}}</p>
        <p class="card-text">Incorrect answers: {{wrong}}</p>
        <p class="card-text">Total questions: {{total}}</p>
        <h5>All the best for next quiz!</h5>
</body>
</html>

templates/note-book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NOTE</title>
</head>
<body>

                {% for items in post %}
                            <h2> Name read : {{ items.name_read }}</h2>
                        
                            <p> Node : {{ items.note }}</p>
                {% endfor %}
</body>
</html>

templates/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

{% for comment in postt %}
    <h4><strong>{{comment.author}}</strong></h4>
    <h6><p>{{comment.date}}</p></h6>
    <p>{{comment.body|linebreaks}}</p>
{% endfor %}

{% if user.username %}
    <form action="{% url 'homePage:post' %}" method="POST">
        {% csrf_token %}
        <p><label>Bình luận:</label></p>
        {{form.body}}
        <br/>
        <input type="submit" value="Bình luận"/>
    </form>
{% endif %}


</body>
</html>

templates/readPageSite.html
{% extends "base_homeSite.html" %}

{% load static %}
{% block stylecss %}
<link rel="stylesheet" href="{% static 'css/readPageSite.css' %}">
{% endblock stylecss %}

{% block content %}
<div id="content">
    <div id="content-story">
        <div>
            <h2>{{ object_views.name }}</h2>
        </div>

        <p>{{ object_views.content_reading }}</p>
    </div>
    <div id="content-tab">
        <div id="content-tab-nav">
            <ul>
                <button class="tablinks" onclick="openContentTap(event, 'Quest')">Quest</button>
                <button class="tablinks" onclick="openContentTap(event, 'Vocabulary')">Vocabulary</button>
                <button class="tablinks" onclick="openContentTap(event, 'Note')">Note</button>
            </ul>
        </div>
        <div id="content-tab-body">
            <ul id="body-idiom" class="tabcontent">
                <div>
                    <p class="idiom-idiom" style="font-size: 2em; font-weight: bold;">Break a leg!</p>
                    <p class="idiom-meaning">Good luck! (an expression that is used in theater
                        performances)</p>
                </div>
            </ul>
            <ul id="Quest" class="tabcontent">
                <li>
                    <h1>Welcome to DataFlair Quiz</h1>

                    <div align="right " id="displaytimer"><b>Timer: 0 seconds</b></div>

                    <form method='post' action=''>
                        {% csrf_token %}
                        {% for q in questions%}
                        <div class="form-group">
                            <label for="question">{{q.question}}</label>
                        </div>
                        <div class="form-check">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios1"
                                    value="{{q.op1}}" checked>
                                <label class="form-check-label" for="gridRadios1">
                                    {{q.op1}}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios2"
                                    value="{{q.op2}}">
                                <label class="form-check-label" for="gridRadios2">
                                    {{q.op2}}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios1"
                                    value="{{q.op3}}">
                                <label class="form-check-label" for="gridRadios1">
                                    {{q.op3}}
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios2"
                                    value="{{q.op4}}">
                                <label class="form-check-label" for="gridRadios2">
                                    {{q.op4}}
                                </label>
                            </div>
                            <br>
                        </div>
                        {% endfor %}
                        <input id='timer' type='hidden' name="timer" value="">
                        <br>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    {% block script %}
                    <script>
                        console.log('hello world')
                        const timer = document.getElementById('displaytimer')
                        console.log(timer.textContent)
                        const inputtag = document.getElementById('timer')

                        t = 0
                        setInterval(() => {
                            t += 1
                            timer.innerHTML = "<b>Timer: " + t + " seconds</b>"
                            inputtag.value = t
                        }, 1000)
                    </script>
                    {% endblock script %}
                </li>
            </ul>
            <ul id="Vocabulary" class="tabcontent">
                <li>
                    {% for items in vocabulary %}
                    <p class="">{{ items.vocabulary }} : {{ items.translate }}</p>
                    {% endfor %}
                </li>
            </ul>
            <ul id="Note" class="tabcontent">
                {% if user.username %}
                <form action="" method="POST">
                    {% csrf_token %}
                    <p><label>Note:</label></p>
                    <br/>
                    <input name="note" placeholder="Note now"/>
                </form>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

{% block jscript %}
<script>
    function openContentTap(evt, tabName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(tabName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>
{% endblock jscript %}

templates/readingSite.html
{% extends "base_homeSite.html" %}

{% load static %}
{% block stylecss %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/homePage.css' %}">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock stylecss %}

{% block content %}
<div class="mt-4 container">

    <div id="content-main " \>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a href="#all" class="nav-link active" data-bs-toggle="tab">ALL READING</a>
            </li>
            <li class="nav-item">
                <a href="#funny" class="nav-link" data-bs-toggle="tab">FUNNY STORY </a>
            </li>
            <li class="nav-item">
                <a href="#jokes" class="nav-link" data-bs-toggle="tab">JOKES </a>
            </li>
            <li class="nav-item">
                <a href="#children" class="nav-link" data-bs-toggle="tab">CHILDREN STORY </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade show active" id="all">
                {% for item in object_view %}
                <div class="lesson ">
                    <a href="{% url 'homePage:readPageSite' item.id%}" class="">
                        <a href="{% url 'homePage:readPageSite' item.id%}" class="">
                            <h2>{{ item.name }}</h2>
                        </a>
                        <button type="button" class="btn btn-primary" data-bs-toggle="collapse"
                            data-bs-target="#demo">Read it!</button>

                        <div id="demo" class="collapse">
                            {{ item.content_reading }}
                        </div>
                </div>
                {% endfor %}
            </div>
            <div class="tab-pane fade" id="funny">
                {% for item in object_view1 %}
                <div class="lesson ">
                    <h2>{{ item.name }}</h2>
                    <button type="button" class="btn btn-primary" data-bs-toggle="collapse"
                        data-bs-target="#demo">Simple collapsible</button>
                    <div id="demo" class="collapse">
                        <p class="" style="color: white;">{{ item.content_reading }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="tab-pane fade" id="jokes">
                {% for item in object_view2 %}
                <div class="lesson">
                    <h2>{{ item.name }}</h2>
                    <button type="button" class="btn btn-primary" data-bs-toggle="collapse"
                        data-bs-target="#demo">Simple collapsible</button>
                    <div id="demo" class="collapse">
                        {{ item.content_reading }}
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="tab-pane fade" id="children">
                {% for item in object_view3 %}
                <div class="lesson ">
                    <h2>{{ item.name }}</h2>
                    <button type="button" class="btn btn-primary" data-bs-toggle="collapse"
                        data-bs-target="#demo">Simple collapsible</button>
                    <div id="demo" class="collapse">
                        {{ item.content_reading }}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <script>
            document.addEventListener("DOMContentLoaded", function () {
                var tabList = [].slice.call(document.querySelectorAll("#myTab a"));
                tabList.forEach(function (tab) {
                    var tabTrigger = new bootstrap.Tab(tab);

                    tab.addEventListener("click", function (event) {
                        event.preventDefault();
                        tabTrigger.show();
                    });
                });
            });
        </script>
    </div>

</div>
{% endblock content %}

templates/signIn.html
{% extends "base_signSite.html" %}
{% load crispy_forms_tags %}
{% block signSite %}
<div>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <label>Sign In</label>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign In</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'signSite:signUp' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
</div>
{% endblock signSite %}

templates/signOut.html
{% extends "base_signSite.html" %}
{% load crispy_forms_tags %}
{% block signSite %}
<div>
    <h2>You have been signed out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'signSite:signIn' %}">Sign In</a>
        </small>
    </div>
</div>
{% endblock signSite %}

templates/signUp.html
{% extends "base_signSite.html" %}
{% load crispy_forms_tags %}
{% block signSite %}
<div>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <label class="border-bottom mb-4">Join Today</label>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'signSite:signIn' %}">Sign In</a>
            </small>
        </div>
    </div>
</div>
{% endblock signSite %}